---
ID: "bc0b8e49-a7e9-4a7e-87ad-d5ae9910d227"
Parent: "ba07af03-314b-49dd-92f7-1ee330bd63e0"
Template: "86864760-3b8b-4e79-927e-0addcd14055d"
Path: "/sitecore/content/MvpSite/Shared Content/Hero/Homepage-Application teaser"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "00f0228c-aff3-4ab7-ac98-e4175a53bf32"
      Hint: HeroTitle
      Value: Sitecore MVP Application process
    - ID: "066f7e92-30ad-4198-b138-b40ccaec6d20"
      Hint: HeroLink
      Value: |
        <link text="Learn more about the process" anchor="" linktype="internal" class="" title=""  querystring="" id="{47E6AB4B-97FB-4C14-A3D6-6265F41723DB}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200624T085353Z
    - ID: "3489c7a2-efe1-49e0-a3d7-271183c4f255"
      Hint: HeroImage
      Value: |
        <image mediaid="{75E92DFC-F50D-40C7-824F-EEEB8D58B5D6}" />
    - ID: "53ee3e16-ba10-4013-959e-9a652a533845"
      Hint: HeroSubtitle
      Value: Application
    - ID: "69db2d7e-db5e-4a02-8580-0bcfb77b5482"
      Hint: HeroDescription
      Value: "Working with your mentor towards wider engagement with the Sitecore community? You might be an MVP!"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "96b86e72-e7dc-4bf3-92cc-9244c7021996"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220305T111333Z
